AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    content-sharing-app

    Sample SAM Template for content-sharing-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3
        MemorySize: 128

        Tracing: Active
    Api:
        TracingEnabled: true
        Cors:
            AllowMethods: "'GET,POST,OPTIONS,PUT,DELETE'"
            AllowHeaders: "'content-type'"
            AllowOrigin: "'*'"
Resources:
    GetTextFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: handler/
            Handler: getText.lambda_handler
            Runtime: python3.9
            Architectures:
                - x86_64
            Events:
                GetText:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /text
                        Method: get
    PostTextFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: handler/
            Handler: postText.lambda_handler
            Runtime: python3.9
            Architectures:
                - x86_64
            Events:
                PostText:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /text
                        Method: post

Outputs:
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    UploadApi:
        Description: API Gateway endpoint URL for Prod stage for Content Sharing function
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/'
    UploadFunction:
        Description: Content Sharing Lambda Function ARN
        Value: !GetAtt UploadFunction.Arn
    UploadFunctionIamRole:
        Description: Implicit IAM Role created for Content Sharing function
        Value: !GetAtt UploadFunctionRole.Arn
